spring:
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 3000
            response-timeout: 75s
          metrics:
            enabled: true

management:
  endpoint:
    health:
      show-details: never
